name: "my_project"
version: "1.0.0"
config-version: 2

profile: "redshift"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["data"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "dbt_packages"

models:
  my_project:
    +materialized: table

seeds:
  quote_columns: false
  schema: analytics
