name: my_dbt_project
profile: snowflake
config-version: 2
version: 1.0

models:
  my_dbt_project:
    +materialized: table
    +pre-hook: "{% if execute %}{% do log('>>>>> pre-hook: ' ~ invocation_id, True) %}{% endif %}"
    +post-hook: "{% if execute %}{% do log('>>>>> post-hook: ' ~ invocation_id, True) %}{% endif %}"
    +sql_header: "{{ 'CALL SYSTEM$WAIT(' ~ var('wait_seconds', 1) ~ ');' }}"

on-run-start: "{% if execute %}{% do log('>>>>> on-run-start: ' ~ invocation_id, True) %}{% endif %}"
on-run-end: "{% if execute %}{% do log('>>>>> on-run-end: ' ~ invocation_id, True) %}{% endif %}"
