name: my_dbt_project
profile: snowflake
config-version: 2
version: 1.0

models:
  my_dbt_project:
    +materialized: table
    +sql_header: "{{ 'CALL SYSTEM$WAIT(' ~ var('wait_seconds', 1) ~ ');' }}"
