name: my_dbt_project
profile: snowflake
config-version: 2
version: 1.0

models:
  my_dbt_project:
    +materialized: table
    +pre-hook: "{% if execute %}{% do print('⇨⇨⇨⇨ pre-hook: ' ~ invocation_id) %}{% endif %}"
    +post-hook: "{% if execute %}{% do print('⇨⇨⇨⇨ post-hook: ' ~ invocation_id) %}{% endif %}"
    +sql_header: "{{ 'CALL SYSTEM$WAIT(' ~ var('wait_seconds', 1) ~ ');' }}"

on-run-start: "{% if execute %}{% do print('⇨⇨⇨⇨ on-run-start: ' ~ invocation_id) %}{% endif %}"
on-run-end: "{% if execute %}{% do print('⇨⇨⇨⇨ on-run-end: ' ~ invocation_id) %}{% endif %}"
