name: "snowflake"
version: "1.0.0"
config-version: 2

profile: "snowflake"

source-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

vars:
  division: ""

models:
  snowflake:
    +materialized: table
    +schema: "{{ 'dbt_jyeo' ~ var('division', '') }}"
