name: "my_dbt_project"
version: "1.0.0"
config-version: 2

profile: "snowflake"

macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "logs"
  - "target"
  - "dbt_modules"
  - "dbt_packages"

models:
  my_dbt_project:
    +materialized: table

quoting:
  identifier: true
