# version: 2

# sources:
#   - name: dbt_jyeo
#     tables:
#       - name: people
#         external:
#           location: "gs://dbt-external-tables-testing/csv/*"
#           options:
#             format: csv
#             skip_leading_rows: 1
#         columns:
#           - name: id
#             data_type: int64
#           - name: first_name
#             data_type: string
#           - name: last_name
#             data_type: string
#           - name: email
#             data_type: string
