name: "my_dbt_project"
version: "1.0.0"
config-version: 2

profile: "spark"

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  my_dbt_project:
    +materialized: table
    +file_format: delta

tests:
  +store_failures: true
  +file_format: delta
