name: "my_dbt_project"
version: "1.0.0"
config-version: 2

profile: "databricks"

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  my_dbt_project:
    +materialized: table
    bravo:
      +schema: doesnt_exist_or_unauthorized
    # +file_format: delta
