name: "databricks"
version: "1.0.0"
config-version: 2

profile: "databricks"

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  databricks:
    +materialized: table
