version: 2

sources:
  # A standard regular source pointing to an already existing table.
  - name: sandbox_dataset
    tables:
      - name: customers
        columns:
          - name: user_id
          - name: user_name
  # A source derived from an external GCP Cloud SQL connection. Note the quoting.
  - name: external
    tables:
      - name: customers
        identifier: >
          EXTERNAL_QUERY("us.bq_cloud_sql_connection", "SELECT * FROM customers")
        quoting:
          database: false
          schema: false
          identifier: false
        columns:
          - name: user_id
          - name: user_name
