version: 2

sources:
  - name: source
    database: "{{ var('dev_prefix', '') ~ 'elopm' ~ var('dev_suffix', '') }}"    
    schema: dbt_jyeo
    tables:
      - name: my_source

# dbt run --vars "{'dev_prefix': 'dev', 'dev_suffix': 'ent'}" 
# should set database to be 'development'
