version: 2

sources:
  - name: dbt_jyeo
    database: |
      {%- if "_dev_" in target.database|lower -%} raw
      {%- else -%} {{ target.database }}
      {%- endif -%}
    schema: |
      dbt_jyeo
    tables:
      - name: my_source_foo
      - name: my_source_bar_1
        identifier: bar
