version: 2

sources:
  - name: dbt_jyeo
    loaded_at_field: updated_at
    freshness:
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: my_source_a
