name: "bigquery"
version: "1.0.0"
config-version: 2

profile: "bigquery"

data-paths: ["seeds"]
source-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "dbt_packages"

models:
  bigquery:
    +materialized: table
