name: "bigquery"
version: "1.0.0"
config-version: 2

profile: "bigquery"

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "dbt_packages"

models:
  bigquery:
    +materialized: incremental
    +incremental_strategy: insert_overwrite
    +partition_by:
      field: updated_at
      data_type: timestamp
      granularity: day
