name: Print GitHub Action debug info
on:
  pull_request:
    types: [opened, synchronize, closed, reopened]

jobs:
  pr_job:
    name: Print info
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"
          echo "${{ github.event_name }}"
